version: '3.7'

services:
  osm-tirex:
    build:
      context: .
      shm_size: '2GB'
    shm_size: '2GB'
    image: "osm-tirex"
    ports:
      - 8000:80
      - 8090:8080
      # - 5432:5432
    volumes:
      - data:/data/database/
      - tiles:/data/tiles/
      - style:/data/style/
      - config:/data/config/
      - /home/osm/osm-downloads/prince-edward-island-latest.osm.pbf:/data/region.osm.pbf
      - /home/osm/osm-downloads/:/data/downloads/
    environment:
      # - FLAT_NODES=enabled
      - THREADS=4
      - CACHE=2500
      #cpuset: 28-31
      #mem_limit: 16GB
      # deploy:
      #     resources:
      #         limits:
      #           cpus: '4.00'
      #           memory: 16GB
      # reservations:
      #   cpus: 0.25
      #   memory: 128M

      # command: "import"
    command: "run"
    # command: "debug"

volumes:
  data:
  tiles:
  style:
  config:
